[package]
name = "mini_gpu"
version = "0.1.0"
edition = "2021"

[dependencies] 
bytemuck = { version = "1.13", features = ["derive"] }
env_logger = "0.10.0"
hecs = "0.10.3"
image = "0.24.6"
pollster = "0.3.0"
wgpu = "0.16.1"
winit = "0.28.6"


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.87"
